name: Build My Dist

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04 # 换个稍微稳一点的系统

    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16 # 换到 16，因为它处于新旧交替的边缘，兼容性最强

      - name: 强制安装依赖
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps

      - name: 执行编译
        # 这里是关键：通过环境变量开启老项目的兼容模式
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm run build

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: EZ-THEME-DIST
          path: dist/
